/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rednum_com_infbigand_Security_En_Dn_crypt */

#ifndef _Included_rednum_com_infbigand_Security_En_Dn_crypt
#define _Included_rednum_com_infbigand_Security_En_Dn_crypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    encode
 * Signature: ([C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_encode
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    decode
 * Signature: ([C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_decode
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    getDecodeKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_getDecodeKey
  (JNIEnv *, jclass);

/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    getEncryptKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_getEncryptKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
