/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rednum_com_infbigand_Security_En_Dn_crypt */

#ifndef _Included_rednum_com_infbigand_Security_En_Dn_crypt
#define _Included_rednum_com_infbigand_Security_En_Dn_crypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    encode
 * Signature: ([C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_encode (JNIEnv *env, jclass jobj, jcharArray char_array){
    char code[100];
    char temp_char,trans_char;
    int temp_num,trans_num;

    // Get the char array's length
    int len = (*env)->GetArrayLength(env, char_array);

    // Get the first char in this char array
    jchar* p = (*env)-> GetCharArrayElements(env,char_array,0);


    for(int i = 0; i < len; i++) {
        temp_char = *(p+i); // get the char when its index is i
        if (temp_char <= 'z' && temp_char >= 'a')
            temp_num = temp_char - 'a' + 1;
        else if (temp_char <= 'Z' && temp_char >= 'A')
            temp_num = temp_char - 'A' + 27;

        trans_num = temp_num*3 % 52;

        if (trans_num > 26 && trans_num <= 52)         //Transform number to character
            trans_char = 'A' + trans_num - 27;
        else if (trans_num > 0 && trans_num <= 26)
            trans_char = 'a' + trans_num - 1;

        code[i] = trans_char; // put char into char array which will be returned
    }
    code[len] = '\0';

    return (*env)->NewStringUTF(env, code);
}

/*
 * Class:     rednum_com_infbigand_Security_En_Dn_crypt
 * Method:    decode
 * Signature: ([C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rednum_com_infbigand_Security_En_1Dn_1crypt_decode (JNIEnv *env, jclass jobj, jcharArray char_array){
    int n;
    char prim[100];
    char temp_char,trans_char;
    int temp_num,trans_num;

    // Get the char array's length
    int len = (*env)->GetArrayLength(env, char_array);

    // Get the first char in this char array
    jchar* p = (*env)-> GetCharArrayElements(env,char_array,0);

    for(int i = 0;i < len;i++) {
        temp_char = *(p+i);             //Consider about the corresponding digit of character
        if (temp_char <= 'z' && temp_char >= 'a')
            temp_num = temp_char - 'a' + 1;
        else if (temp_char <= 'Z' && temp_char >= 'A')
            temp_num = temp_char - 'A' + 27;

        n = temp_num % 3;  //Mode 3 and compute primitive number
        switch(n) {
            case 0:
                trans_num = temp_num/3;
                break;
            case 1:
                trans_num = 35 + temp_num/3;
                break;
            case 2:
                trans_num = 18 + temp_num/3;
                break;
            default:
                break;
        }
        //Transform number to character
        if (trans_num > 26 && trans_num <= 52)
            trans_char = 'A' + trans_num - 27;
        else if (trans_num > 0 && trans_num <= 26)
            trans_char = 'a' + trans_num - 1;

        prim[i] = trans_char;
    }
    prim[len] = '\0';
    return (*env)->NewStringUTF(env, prim);
}

#ifdef __cplusplus
}
#endif
#endif
